### ISSUE TITLE
Deploy web ui

### ISSUE THREAD

**Issue by DimmKirr** [influxdata/ansible-influxdb-enterprise#10]
Hello. What are the plans to deploy enterprise web ui application? 
By chance, is it going to be part of this role, is it going to be a docker image or none of the above?

Thank you.

**Comment by pmyjavec** [comment]
Hello @kireevco,

The WebUI will soon be replaced by our open source product known as Chronograf, I would rather not spend too much time on supporting the Web UI for this reason.
 
I've been told the latest Chronograf is essentially a drop in replacement for the WebUI and there is a  blog post about some of the new features here: https://www.influxdata.com/chronograf-beta-update-dashboards-databases-graph-types-oh/

Let me know what you think :)

**Comment by DimmKirr** [comment]
Do you mean https://docs.influxdata.com/enterprise/v1.2/production_installation/web_console_installation/ ?

**Comment by DimmKirr** [comment]
@pmyjavec any update on this? We're really looking forward to deploy web console via ansible

**Comment by pmyjavec** [comment]
Hello @kireevco, 

I mean the Web Console is being phased out in favour of Chronograf, so it would be best to deploy the latest Chronograf using Ansible, in favour of spending time on the web console deployment. 

Hopefully that makes sense? 

Pauly

**Comment by DimmKirr** [comment]
@pmyjavec I still don't get it. Does Chronograf also have cluster management capabilities?
I'm talking specifically about the Enterprise UI.

**Comment by gunnaraasen** [comment]
@kireevco Yes, most of the Enterprise UI cluster management features have already been ported to Chronograf. The goal is to eventually sunset the Enterprise UI and focus on adding new cluster management features to Chronograf going forward.

**Comment by pmyjavec** [comment]
Hello @kireevco, I'm going to close this off as Chronograf is the recommended tool for the job now.

We have a Chronograf module available at https://galaxy.ansible.com/influxdata/, please let me know if we can help you out at all with this in the future.

Thanks
