### ISSUE TITLE
adding node to a cluster

### ISSUE THREAD

**Issue by HIMADRI518** [influxdata/ansible-influxdb-enterprise#15]
I am building an influx cluster in AWS and when I try a node(private instance) to the cluster, I am getting the following error,  "add-meta: operation exited with error: no leader". I am not sure what is causing this error. Any ideas?

**Comment by pmyjavec** [comment]
@HIMADRI518, would it be possible to see a snippet of the error? 

Sorry I didn't reply earlier.

**Comment by HIMADRI518** [comment]
No problem, I was able to resolve it. Thanks!

**Comment by Reddy1985** [comment]
Hi, how did you solve this problem?
