### ISSUE TITLE
Can this become an actual role which can be installed via requirements.yml?

### ISSUE THREAD

**Issue by DimmKirr** [influxdata/ansible-influxdb-enterprise#4]
Thank you for maintaining this Ansible role, but It's highly inconvenient not to be able to require this role / version from requirements.yml as well as not being able to control versioning.

All you need is to make sure directories like roles, defaults etc are located in the root of the repo.

So I suggest that you create `influxdata/ansible-influxdb-enterprise` with this structure and submodule it into `influxdata/ansible` if needed.

(For now I will be using it from here https://github.com/kireevco/ansible-influxdb-enterprise)

**Comment by pmyjavec** [comment]
Hello @kireevco, 

I totally understand your frustration, and apologise for any trouble it may have caused. We're revamping this role to better assist customers with deployments and we really appreciate this feedback. 

I was concerned this might be an issue and was planning to take a closer look at the versioning stuff today, once we've ironed this out I'll let you know.

Thank you,

Pauly

**Comment by DimmKirr** [comment]
Thank you. I would also recommend renaming it to `ansible-influxdb-enterprise` as it would clearly denote Ansible role. 
Could you also publish it to Ansible Galaxy https://galaxy.ansible.com/ ?

In any case, I appreciate such a quick response.

**Comment by pmyjavec** [comment]
Good pick up, thank you!

I've renamed the repo and I will be publishing this to Galaxy today, I was actually just working on that.

**Comment by pmyjavec** [comment]
@kireevco,

Here you go, https://galaxy.ansible.com/influxdata/influxdb-enterprise/

Cheers, 

Pauly

**Comment by DimmKirr** [comment]
Alright. Thank you!
-- 
Sincerely,
  Dmitry Kireev
  Cell: +1 (818) 850-55-77
  Skype: kireev.co
