### ISSUE TITLE
Remove redundant quotes

### ISSUE THREAD

**Issue by DimmKirr** [influxdata/ansible-influxdb-enterprise#7]
There are many places where quotes are used, although they are redundant in YAML. For instance:
`owner: 'influxdb'`

I propose to clean it up.

**Comment by pmyjavec** [comment]
@kireevco,

Quoting all strings that do not contain variables with single quotes make for a consistent experience when working with the playbooks, looks better in some editors and things don't explode when a colon is used.

Also, remember all files in Ansible are actually Jinja templates and sometimes the quotes do matter, so I feel it makes things ultimately simpler.

If anything it would be better to go full single quotes like these guys do: https://github.com/whitecloud/ansible-styleguide#quotes

**Comment by DimmKirr** [comment]
@pmyjavec I hear you, but seems like colon is the only gotcha.
Consistency is a relative thing. There are many community roles/playbooks that are following the `no-quote` pattern. So using quotes where they are not required actually makes it inconsistent.

I'm referring to common community examples http://docs.ansible.com/ansible/YAMLSyntax.html  and https://www.jeffgeerling.com/blog/yaml-best-practices-ansible-playbooks-tasks. Styling guide is pretty clear.

Also I'm referring to roles from the top of ansible galaxy (many of them are from geerlingguy) like
- https://galaxy.ansible.com/geerlingguy/redis/
- https://galaxy.ansible.com/geerlingguy/java/
- https://galaxy.ansible.com/geerlingguy/mysql/

At the end of the day it becomes a preference.
